### ISSUE TITLE
Include config schema version

### ISSUE THREAD

**Issue by jack-berg** [MrAlias/otel-schema#11]
We should include some sort of version specification in configuration files to help with parsing and schema evolution.

Example:
```yaml
version: 0.1
sdk: ..
instrumentation ...
```

The idea of a document self describing the version it adheres to is pretty common. It shows up in [docker compose](https://docs.docker.com/compose/compose-file/compose-versioning/) files, [kubernetes yaml](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/#required-fields) and many other places.

**Comment by codeboten** [comment]
I agree this makes sense, i propose this as the first section of the config file we agree on and commit to the "official" kitchen sink :)
